CREATE DATABASE QUAN_20098151
        ON PRIMARY
        (NAME = '20098151_Data',
         FILENAME = 'D:\SQL_DATA\20098151_Data.mdf',
         SIZE = 20MB,
         MAXSIZE = 40MB,
         FILEGROWTH = 1MB)
        LOG ON
        (NAME = '20098151_Log',
         FILENAME = 'D:\SQL_DATA\20098151_Log.ldf',
         SIZE = 6MB,
         MAXSIZE = 8MB,
         FILEGROWTH = 1MB)
--TẠO CÁC TABLE
CREATE TABLE DANHMUCTHUOC
	(MATHUOC CHAR(5) PRIMARY KEY,
	 TENTHUOC NVARCHAR(40) NOT NULL,
	 DONVITINH NVARCHAR(20) NOT NULL,
	 NOISANXUAT NVARCHAR(40),
	 NGAYSANXUAT DATETIME CHECK (NGAYSANXUAT < GETDATE()),
	 HANDUNG NVARCHAR(20))
CREATE TABLE KHACHHANG
	(MAKHACHHANG CHAR(5) PRIMARY KEY,
	 HOLOT NVARCHAR(40) NOT NULL,
	 TENKH NVARCHAR(20) NOT NULL,
	 DIACHI NVARCHAR(40),
	 DIENTHOAI CHAR(10) CHECK (DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
CREATE TABLE PHIEUNHAPXUAT
	(MAPHIEU CHAR(5) PRIMARY KEY,
	 NGAY DATETIME,
	 MAKHACHHANG CHAR(5) REFERENCES KHACHHANG(MAKHACHHANG),
	 LOAIPHIEU CHAR(1))

CREATE TABLE CTNHAPXUAT	
	(MAPHIEU CHAR(5) REFERENCES PHIEUNHAPXUAT(MAPHIEU),
	 MATHUOC CHAR(5) REFERENCES DANHMUCTHUOC(MATHUOC),
	 SOLUONG INT,
	 DONGIA MONEY)


INSERT INTO DANHMUCTHUOC VALUES('Dec1', 'Decolgen', N'viên', 'ho chi minh', '1/2/2005', '3 nam')
INSERT INTO DANHMUCTHUOC VALUES('Eff5', 'Decolgen 1', N'viên', 'ho chi minh', '1/2/2005', '3 nam')
INSERT INTO DANHMUCTHUOC VALUES('Par4', 'Decolgen 2', N'viên', 'ho chi minh', '1/2/2005', '3 nam')
INSERT INTO DANHMUCTHUOC VALUES('Ups2', 'Decolgen 3', N'viên', 'ho chi minh', '1/2/2005', '3 nam')

INSERT INTO KHACHHANG VALUES('KH001', 'Nguyen van', N'An', 'ho chi minh', '0123456789')
INSERT INTO KHACHHANG VALUES('KH002', 'Nguyen van', N'An', 'ho chi minh', '0123456789')
INSERT INTO KHACHHANG VALUES('KH003', 'Nguyen van', N'An', 'ho chi minh', '0123456789')
INSERT INTO KHACHHANG VALUES('KH004', 'Nguyen van', N'An', 'ho chi minh', '0123456789')

INSERT INTO PHIEUNHAPXUAT VALUES('P002', '9/5/2005', 'KH001', 'B')
INSERT INTO PHIEUNHAPXUAT VALUES('P003', '9/5/2005', 'KH001', 'B')

INSERT INTO CTNHAPXUAT VALUES('P002', 'Dec1', 10, 2750)
INSERT INTO CTNHAPXUAT VALUES('P002', 'Ups2', 10, 2750)
INSERT INTO CTNHAPXUAT VALUES('P003', 'Dec1', 10, 2750)
INSERT INTO CTNHAPXUAT VALUES('P003', 'Par4', 10, 2750)



INSERT INTO DANHMUCTHUOC VALUES('Dec3', 'Decolgen', N'Viên', 'Cty United Pharma VN', '02/2005', '3 nam')
INSERT INTO DANHMUCTHUOC VALUES('Eff5', 'Efferalgan', N'Viên', 'Cty Upsa Conseil', '07/2005', '5 nam')
INSERT INTO DANHMUCTHUOC VALUES('Par4', 'Paracetamol', N'Viên', 'Cty United Pharma VN', '09/2005', '4 nam')
INSERT INTO DANHMUCTHUOC VALUES('Ups2', 'Upsa-C', N'viên', 'Cty Upsa Conseil', '02/2004', '2 nam')

INSERT INTO KHACHHANG VALUES('KH001', N'Nguyễn Văn', N'An', N'123 Ông Ích Khiêm', '051O123456')
INSERT INTO KHACHHANG VALUES('KH002', N'Mai Thị', N'Lựu', N'90 Phan Thanh', '0905123456')
INSERT INTO KHACHHANG VALUES('KH003', N'Phan Anh', N'Thư', N'12/2 Nguyễn Văn Linh', '0913123456')
INSERT INTO KHACHHANG VALUES('KH004', N'Đào Thị', N'Na', N'50/5 Nguyễn Trãi', '0985123456')

INSERT INTO PHIEUNHAPXUAT VALUES('P002', '09/05/2005', 'KH001', 'B')
INSERT INTO PHIEUNHAPXUAT VALUES('P003', '10/04/2005', 'KH003', 'B')

INSERT INTO CTNHAPXUAT VALUES('P002', 'Dec3', 10, 2750)
INSERT INTO CTNHAPXUAT VALUES('P002', 'Ups2', 5, 2500)
INSERT INTO CTNHAPXUAT VALUES('P003', 'Dec3', 1, 2750)
INSERT INTO CTNHAPXUAT VALUES('P003', 'Par4', 10, 2000)

SELECT * FROM DANHMUCTHUOC
SELECT * FROM KHACHHANG
SELECT * FROM PHIEUNHAPXUAT
SELECT * FROM CTNHAPXUAT

-- VIẾT HÀM CHO BIẾT LOẠI THUỐC MÀ KHÁCH HÀNG DÙNG, VỚI MÃ KHÁCH HÀNG ĐƯỢC NHẬP TỪ BÀN PHÍM
GO
CREATE FUNCTION cau1 (@makh CHAR(5))
RETURNS CHAR(5)
AS
BEGIN
    DECLARE @loaithuoc CHAR(5)
    SELECT @loaithuoc = CTNHAPXUAT.MATHUOC
    FROM KHACHHANG
        INNER JOIN PHIEUNHAPXUAT
            ON KHACHHANG.MAKHACHHANG = PHIEUNHAPXUAT.MAKHACHHANG
        INNER JOIN CTNHAPXUAT
            ON PHIEUNHAPXUAT.MAPHIEU = CTNHAPXUAT.MAPHIEU
    WHERE @makh = KHACHHANG.MAKHACHHANG
    RETURN @loaithuoc
END

drop function cau1 

DECLARE @makh CHAR(5)
SET @makh = 'KH001'
PRINT N'KHÁCH HÀNG ' + CONVERT(CHAR(5),@makh) + N' DÙNG THUỐC CÓ MÃ ' + CONVERT(CHAR(5) ,dbo.cau1(@makh))


