CREATE TRIGGER TRG_KHACHAHNG ON KHACHHANG
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @makh INT
	SET @makh = (SELECT MAKHACHHANG FROM INSERTED)
	IF EXISTS (SELECT * FROM KHACHHANG WHERE MAKHACHHANG=@makh)
		BEGIN
			PRINT 'DA TON TAI'
			ROLLBACK TRAN
		END
END

INSERT INTO KHACHHANG(MAKHACHHANG, TENCONGTY) VALUES (6, 'THU NGHIEM')



-- XOA TRIGGER
DROP TRIGGER TRG_KHACHAHNG

SELECT * FROM KHACHHANG

CREATE TRIGGER TRG_KHACHHANG ON KHACHHANG
INSTEAD OF INSERT			-- TRIGGER TRUOCWS KHI CHEN OR DÙNG INSTEAD FOR
AS
BEGIN
	DECLARE @makh INT
	SET @makh = (SELECT MAKHACHHANG FROM INSERTED)		-- BANG MAC DINH TREN BO NHO KHI GOI INSERT
	IF EXISTS (SELECT * FROM KHACHHANG WHERE MAKHACHHANG = @makh)
		PRINT 'MAKHACHHANG DA TON TAI'
	ELSE
		INSERT INTO KHACHHANG SELECT * FROM INSERTED
END


INSERT INTO KHACHHANG(MAKHACHHANG, TENCONGTY) VALUES (7, 'THU NGHIEM')


-- VIẾT MỘT TRIGGER CHO BẢNG KHÁCH HÀNG KHI THỰC HIỆN XÓA MỘT HÀNG NÀO ĐÓ. NẾU KHÔNG TỒN TẠI KHÁCH HÀNG NÀY THÌ THÔNG BÁO, NGƯỢC LẠI THCỰ HIỆN XÓA
SELECT * FROM KHACHHANG
--DELETE
DELETE FROM KHACHHANG WHERE MAKHACHHANG = 1

DROP TRIGGER DEL_KHACHHANG
-- CREATE TRIGGER
GO
CREATE TRIGGER DEL_KHACHHANG ON KHACHHANG
INSTEAD OF DELETE
AS	BEGIN
	DECLARE @makh INT
	SET @makh = (SELECT MAKHACHHANG FROM DELETED)
	IF EXISTS (SELECT * FROM KHACHHANG WHERE @makh = MAKHACHHANG)
			DELETE FROM KHACHHANG WHERE @makh = MAKHACHHANG
	ELSE
		PRINT 'KHONG TON TAI '
END