CREATE DATABASE QLSACH
ON PRIMARY (NAME = 'QLSACH_DATA',
            FILENAME = 'D:\SQL_DATA\QLSACH_DATA.MDF',
            SIZE = 20MB,
            MAXSIZE = 40MB,
            FILEGROWTH = 1MB)
LOG ON (NAME = 'QLSACH_LOG',
        FILENAME = 'D:\SQL_DATA\QLSACH_LOG.LDF',
        SIZE = 6MB,
        MAXSIZE = 8MB,
        FILEGROWTH = 1MB)
GO
CREATE TABLE NHOMSACH
    (
        MANHOM  CHAR(5) PRIMARY KEY,
        TENNHOM NVARCHAR(25)
    )
GO
CREATE TABLE NHANVIEN
    (
        MANV     CHAR(5) PRIMARY KEY,
        HOLOT    NVARCHAR(25),
        TENNV    NVARCHAR(10),
        PHAI     NVARCHAR(3),
        NGAYSINH SMALLDATETIME,
        DIACHIA  NVARCHAR(40)
    )
GO
CREATE TABLE DANHMUCSACH
    (
        MASACH  CHAR(5) PRIMARY KEY,
        TENSACH NVARCHAR(60),
        TACGIA  NVARCHAR(60),
        MANHOM  CHAR(5) REFERENCES NHOMSACH(MANHOM),
        DONGIA  NUMERIC(5),
        SLTON   NUMERIC(5)
    )
GO
CREATE TABLE HOADON
    (
        MAHD    CHAR(5) PRIMARY KEY,
        NGAYBAN SMALLDATETIME,
        MANV    CHAR(5) REFERENCES NHANVIEN(MANV)
    )
GO
CREATE TABLE CHITIETHOADON
    (
        MAHD    CHAR(5) REFERENCES HOADON(MAHD),
        MASACH  CHAR(5) REFERENCES DANHMUCSACH(MASACH),
        SOLUONG NUMERIC(5)
    )
GO
--CHÈN DỮ LIỆU VÀO BẢNG NHOMSACH
INSERT INTO NHOMSACH VALUES ('N001', N'KỸ THUẬT TRỒNG TRỌT')
GO

--CHÈN DỮ LIỆU VÀO BẢNG DANHMUCSACH
INSERT INTO DANHMUCSACH VALUES ('S111', N'Đèn không hắt bóng', N'Dzunichi Watanabe (Cao Xuân Hao dịch)', 'N001', 55000, 45)
GO
INSERT INTO DANHMUCSACH VALUES ('S112', N'Kỹ thuật trồng hoa phong lan', N'Nguyễn Lân Hùng', 'N001', 45000, 35)
GO
--INSERT INTO DANHMUCSACH VALUES ('S113', N'Kỹ thuật chăm sóc hoa mai', N'Lê Xuân A', 'N007', 35000, 15)
GO
INSERT INTO DANHMUCSACH VALUES ('S114', N'Kỹ thuât chăm sóc cây cam', N'Trần Ha', 'N001', 24000, 12)
GO

--CHÈN DỮ LIỆU VÀO BẢNG NHANVIEN
INSERT INTO NHANVIEN VALUES ('NV001', N'Nguyễn Văn', N'A', N'Nam', '10/10/2002', N'Phường 4, Gò Vấp, HCM')
GO
SELECT * FROM NHANVIEN
GO

--VIẾT CÂU LỆNH ĐỂ SET CSDL QLSACH VỀ CHẾ ĐỘ PHỤC HÔI FULL
-- SET FULLBACKUP CHO DATABASE
ALTER DATABASE QLSACH
SET RECOVERY FULL
GO

--2. TẠO THIẾT BI BACKUP CÓ TÊN QUANLYSACHBACKUP LƯU VÀO TRONG THƯ MỤC ...


--3. THỰC HIÊN CÁC BACKUP SAU CHO CSDL QLSACH, TẤT CẢ BACKUP ĐỀU LƯU VÀO THIẾT BỊ BACKUP VỪA TẠO
	--A. THỰC HIỆN FULL BACKUP CSDL QLSACH
	BACKUP DATABASE QLSACH
	TO DISK = 'D:\SQL_DATA\SQL_SERVER\HQTCSDL\BackupQuanLySach\QuanLySachBackup_Full.bak'	--FILE 1
	GO

	BACKUP DATABASE QLSACH
	TO DISK = 'D:\SQL_DATA\SQL_SERVER\HQTCSDL\BackupQuanLySach\QuanLySachBackup_Diff.bak' WITH DIFFERENTIAL
	GO

	--B. THƯC HIỆN VIỆC INSERT SAU:
	INSERT NHOMSACH VALUES ('N007', 'Truyen ngan')
	GO
	INSERT HOADON VALUES ('11', GETDATE(), 'NV001')
	GO

	BACKUP DATABASE QLSACH
	TO DISK = 'D:\SQL_DATA\SQL_SERVER\HQTCSDL\BackupQuanLySach\QuanLySachBackup_Diff.bak' WITH DIFFERENTIAL
	GO
	--XÓA CSDL, THỰC HIỆN PHỤC HỒI LẠI CSDL QLSACH ĐẾN THỜI ĐIỂM CỦA CÂU B
	--XÓA CSDL
	USE MASTER
	GO
	DROP DATABASE QLSACH
	GO
	--PHỤC HỒI LẠI TẠI THỜI ĐIỂM CỦA CÂU B
	RESTORE DATABASE QLSACH
	FROM DISK = 'D:\SQL_DATA\SQL_SERVER\HQTCSDL\BackupQuanLySach\QuanLySachBackup_Full.bak' WITH NORECOVERY
	GO

	RESTORE DATABASE QLSACH
	FROM DISK = 'D:\SQL_DATA\SQL_SERVER\HQTCSDL\BackupQuanLySach\QuanLySachBackup_Diff.bak'
	GO

	--CHÚ Ý XEM CÓ MẪU TIN VỪA INSERT KHÔNG
	USE QLSACH
	GO
	SELECT * FROM NHOMSACH
	GO
	SELECT * FROM HOADON
	GO



--BACKUP DATABASE WITH DIFFERENTIAL
BACKUP DATABASE QLSACH
TO DISK = 'D:\SQL_DATA\QLSACH_FULLBACKUP_DIFF.BAK' WITH DIFFERENTIAL



BACKUP LOG QLSACH
TO DISK = 'D:\SQL_DATA\QLSACH.TRN'